Add separate sensors for power and current
Maelstrom96/esphome pull request #5
Opened 2021-12-06 13:59 UTC by krconv

Moves the power sensors to be nested under the CT clamps; mainly so that when we figure out how the current sensors work, we won't need to make a breaking change to config

2021-12-06 16:46 UTC, Maelstrom96 requested changes
Looks pretty good other than the lint issues - Will need to do the changes in esphome-docs.

2021-12-06 16:46 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.h
> +  void set_phases(std::vector<PhaseConfig *> phases) { this->phases_ = phases; }
```suggestion
  void set_phases(std::vector<PhaseConfig *> phases) { this->phases_ = std::move(phases); }
```
Can you please reverse this.

2021-12-06 16:46 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.h
> +  void set_ct_clamps(std::vector<CTClampConfig *> ct_clamps) { this->ct_clamps_ = ct_clamps; }
```suggestion
  void set_ct_clamps(std::vector<CTClampConfig *> ct_clamps) { this->ct_clamps_ = std::move(ct_clamps); }
```

2021-12-07 12:43 UTC, krconv commented
I fixed the linting issues in https://github.com/Maelstrom96/esphome/pull/6, sorry for the noise; closing this one

2021-12-07 22:01 UTC, merged